---
title: "Google Mobility"
author: "Samar"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
#Time Series Plot using timetk package
```{r,fig.width=16, fig.height=14}
library(datasets)
library(githubinstall)
library(tidyverse)
library(covdata)
library(ggforce)
library(dplyr)
library(timetk)

b<-google_mobility<-google_mobility %>%
  filter(country_region_code == "US", !is.na(sub_region_1), is.na(sub_region_2)) %>%
  mutate(type = tools::toTitleCase(type)) 

google_mobility %>%
  group_by(type)%>%
    plot_time_series(date,pct_diff,.facet_ncol  = 3, .facet_scales = "free",    # 3-column layout
                     .interactive = FALSE, .x_lab = "time",.y_lab="Percent change from the baseline",.title="Google Mobility Plot")
  
  
b


  
 
```
#Make a seasonality plot
```{r,fig.width=16, fig.height=14}
google_mobility<-google_mobility %>%
  filter(country_region_code == "US", !is.na(sub_region_1), is.na(sub_region_2)) %>%
  mutate(type = tools::toTitleCase(type)) 

google_mobility %>%
  group_by(type)%>%
    plot_seasonal_diagnostics(date,pct_diff,.facet_ncol  = 2,     # 2-column layout
                     .interactive = FALSE,.feature_set = "auto",.x_lab = "time",.y_lab="Percent change from the baseline",.title="Google Mobility Plot")

```

#Google Mobility Data plot using ggplot

```{r,fig.width=16, fig.height=14}

a<-google_mobility %>%
  filter(country_region_code == "US", !is.na(sub_region_1), is.na(sub_region_2)) %>%
  mutate(type = tools::toTitleCase(type)) %>%
  
  
  
  ggplot(mapping = aes(x = date, y = pct_diff,
                       group = sub_region_1)) +
 
  
  geom_line(size = 0.5, color = "gray80") +
  geom_smooth(aes(color = type, group = 1), se = FALSE) +
  facet_wrap(~ type, ncol = 2) +
  labs(x = "Date", y = "Percent Change from Baseline", title = "Relative Trends in Mobility for Kinds of Location in the US, by State",
                              subtitle = "Data are relative to median activity between Jan and june",
       color = "Location Type",
       caption = "Data: Google. Graph: @kjhealy") +
  theme_minimal() +
  theme(legend.position = "top",
        strip.text = element_text(size = rel(1.3)))
a<-a + facet_wrap(. ~ type, scales="free_y")

a
```
#Reference

```{r}

# -------
 # Article title = Mobility Data from Apple and Google,
  #author = Kieran Healy,
  #year = 2020,
  #note = R package version 0.1.0,
  #url = https://kjhealy.github.io/covdata/articles/mobility-data.html

#--------------

```




